### ISSUE TITLE
Handling simultaneous shots.

### ISSUE THREAD

**Issue by mpbl** [PrincetonUniversity/seisflows#4]
*SPECFEM3D* and *SPECFEM3D_GLOBE* both have a feature allowing to launch simultaneous and independent shots in a single MPI job.

A new system class in ```seisflows/seisflows/system/``` is needed.

It needs to have the following features:
* From a number of shot, an optimal job size and the number of processes required by a single job, guess the number of shot to bundle.
* Since there is no fault tolerance (yet), all jobs in a run either fail or succeed, it will require some extra work to be sure that every shot has been performed. Automatically relaunching jobs might be problematic as if the error is on the software side, jobs will be relaunched endlessly.
* The number of shot per run might not be constant. This number depends on a parameter specified in _SPECFEM3D*_ Par_file. A way to handle this without breaking *SeisFlow* solver independance has to be be found.

**Comment by rmodrak** [comment]
My understanding now is that multiple shots can be packaged together into a single job at the workflow level, without having to make modifications to the solver.  (I believe glide-in was the term Shentenu used?)  In the future, I hope that SPECFEM developers could move to this cleaner way of doing things, and also improve the way SPECFEM stores solver/mesh files to reduce I/O overhead.  In the meantime, I'll go ahead and close this issue, and perhaps if anyone is willing to look into "glides in" or consider improvements to the way things are done now in SPECFEM, we could then open up another related issue.
